### ISSUE TITLE
Invalid top-level expression

### ISSUE THREAD

**Issue by FilmKnurd** [stevenschobert/metalsmith-sass#29]
This is not a problem with this plugin, but I'm posting this in case someone else runs into this issue.

Compilation failed for me with
 ```
Metalsmith · [metalsmith-sass] Error: invalid top-level expression -> /Users/veritas/www/hannahsstudio.com/src/styles/style.scss:1:1
```

I thought the issue was with the SASS file or with this plugin. I finally looked at the plugin source code and saw that the data option was set to the file contents. It turns out *all* my files were being processed by the layouts plugin, so the data option had a bunch of HTML templating inside it. I just had to set the patterns option in the layouts plugin to only process markdown files.

This might be a good note to put in the documentation.

**Comment by karneaud** [comment]
thanks for this as I was going nuts trying to figure out what was wrong

**Comment by ismay** [comment]
@karneaud , @FilmKnurd Were you using the [default](https://github.com/superwolff/metalsmith-layouts#default) option? Because if you're not using that, metalsmith-layouts [won't process anything unless it has the `layout` key in the frontmatter](https://github.com/superwolff/metalsmith-layouts/blob/master/test/index.js#L140).

**Comment by karneaud** [comment]
Ohhh...ok

**Comment by ismay** [comment]
@karneaud So that was it? Were you using the `default` option?

**Comment by karneaud** [comment]
Sorry, There was a lot of issue and admit I cannot remember how i solved it. I think it had to do with my files reference and the `metalsmith-ignore`. I do not believe however that it was because of the **"default" ** option

**Comment by ismay** [comment]
Then it shouldn't be a metalsmith-layouts related issue. It'll only process everything if the default option has been set. Otherwise only a `layouts` key will trigger it. If it's behaving otherwise let me know, but so far I don't have any evidence that this is a bug.

**Comment by marr** [comment]
I am hitting this issue as well. Can't seem to figure out how to avoid setting `layout` in the front-matter by utilizing `metalsmith-layouts` `default` property.
This setup works but it requires the `layout` property in my article: https://github.com/marr/metalsmith-project/blob/master/build.js

I would like to avoid that and rely on the default with a build file like this:https://gist.github.com/anonymous/379d3baaee3503050fdc however it errors out with:

```
/Users/dmarr/src/dmarr.io/build.js:19
      throw err;
      ^

Error: [metalsmith-sass] Error: Invalid CSS after "": expected 1 selector or at-rule, was "<!DOCTYPE html>" -> /Users/dmarr/src/dmarr.io/src/scss/styles.scss:1:1
    at Object.callback (/Users/dmarr/src/dmarr.io/node_modules/metalsmith-sass/lib/index.js:69:23)
    at options.error (/Users/dmarr/src/dmarr.io/node_modules/node-sass/lib/index.js:280:32)
```

**Comment by ismay** [comment]
Please move any discussion related to metalsmith-layouts to the metalsmith-layouts repo. Feel free to open an issue there.

To answer your question @marr : 
> This setup works but it requires the layout property in my article: https://github.com/marr/metalsmith-project/blob/master/build.js

With your setup metalsmith-layouts will indeed only process files that have a layout set in the frontmatter. If you're going to use the `default` option it will apply a layout to everything. If you don't want that you can filter with the `pattern` option.

I'll add a note in the readme for the use of the default key and hope that this solves it. If not feel free to open an issue: https://github.com/superwolff/metalsmith-layouts

**Comment by marr** [comment]
Thanks ismay, I will try the `pattern` prop, although it does seem a little counterintuitive. I guess since my layout is `.html`, I would set the pattern to just `'.html'`. From the error and your explanation above, I'd think it was still a -sass issue, since the error is coming from metalsmith-sass and prints "Invalid CSS".

**Comment by ismay** [comment]
I'd use '**/*.html', otherwise it won't match anything.
